FROM eclipse-temurin:21-jre-jammy

COPY spring-ygk-schedule-0.0.1-SNAPSHOT.jar app.jar
COPY oit.html oit.html
COPY oar.html oar.html
COPY oep.html oep.html
COPY mmo.html mmo.html
COPY so.html so.html

ENTRYPOINT ["java","-jar","app.jar"]
