services:
  ygk_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: ygk-bot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/spring-ygk-schedule
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    network_mode: host
    restart: always
    depends_on:
      - db
  db:
    image: postgres:16
    hostname: postgres
    environment:
      - 'POSTGRES_DB=spring-ygk-schedule'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - 5432:5432
    container_name: postgresql_container
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:


